Moved to CVS era.

diff --git a/irchat-mkdist b/irchat-mkdist
--- a/irchat-mkdist
+++ b/irchat-mkdist
@@ -1,6 +1,6 @@
 #! /bin/sh
 #
-# $Id: irchat-mkdist,v 1.10 1999/10/03 10:19:29 tri Exp $
+# $Id: irchat-mkdist,v 1.11 2001/06/07 14:25:09 tri Exp $
 #
 # This file is part of irchat.  Command irchat-mkdist creates 
 # a snapshot of irchat current.  This file itself does not go 
@@ -13,8 +13,6 @@
 
 distfiles=""
 
-clogdir="`finger -l tri | sed -n 's,^.*[Dd]irectory: \([^ ]*/tri\)*.*$,\1/irchat,p' 2>/dev/null | head -1`" 
-
 if [ "x$1" != "x" ] ; then
     distname="irchat-""$1"
 else
@@ -23,62 +21,64 @@ fi
 
 [ -d "$distname" ] && { echo "You have already made $distname today."; exit 1; }
 
-for i in RCS/*,v ; do
-    if [ -f $i ] ; then
-        file=`echo $i | sed 's+^RCS/\(.*\),v$+\1+'`
-        if [ "$file" != "irchat-mkdist" ] ; then
-            distfiles="$distfiles $file"
+mkdir "$distname"
+[ $? -ne 0 ] &&  { echo "Unable to make distdir $distname."; exit 1; }
+
+( date -u '+%a %b %d %H:%M:%S  IRCHAT Distribution Generator <irchat@rinne.iki.fi>' ;
+  echo '' ;
+  echo '	* Generated release '"$distname"'.' ;
+  echo '' ;
+  cat ChangeLog ) > ChangeLog.new
+
+for i in * ; do
+    if [ -f "$i" ] ; then
+        if [ "$i" = "irchat-mkdist" ] ; then
+            echo 'Skipped irchat-mkdist.'
+        elif [ "$i" = "ChangeLog" ] ; then
+            echo 'Skipped ChangeLog.'
+        elif [ "$i" = "ChangeLog.new" ] ; then
+            cp -p ChangeLog.new "$distname"/ChangeLog
+            rm -f ChangeLog.new
+        else
+            cp -p "$i" "$distname"
+            [ $? -ne 0 ] &&  { echo "Unable to copy file $i."; exit 1; }
+            distfiles="$distfiles $i"
         fi
     fi
 done
 
-for i in $distfiles ; do
-    co $i
-    if [ $? -ne 0 ] ; then
-        exit 1
-    fi
-done
+rm -f "$distname"/*.elc
 
-co -l irchat-version.el &&
-     ci -u -f -m"Irchat mkdist." irchat-version.el &&
-     co irchat-version.el &&
-     mkdir "$distname" &&
-     cp $distfiles "$distname" &&
-     ( if [ -f "$clogdir/ChangeLog" -a -r "$clogdir/ChangeLog" ]
-       then
-           cp "$clogdir/ChangeLog" "$distname"
-       fi
-       true ) &&
-     ( cd "$distname" &&
-       ttt="/tmp/xxx.$$"
-       rm -f "$ttt"
-       for i in ./*
-       do
-         cat "$i" | gawk 'BEGIN { s = 1; }
-                         { if      (match($0, "^... BEGIN NODIST")) { s = 0 }
-                           else if (match($0, "^... END NODIST"))   { s = 1 }
-                           else if (s == 1) { print $0 } }' > "$ttt"
-         rm -f "$i"
-         cat "$ttt" > "$i"
-         rm -f "$ttt"
-       done
-       true ) &&
-     chmod 755 "$distname" &&
-     (
-          cd "$distname" &&
-          gmake xemacs-compact &&
-          mv irchat.elc irchat-xemacs-elc &&
-          gmake gnuemacs-compact &&
-          mv irchat.elc irchat-gnuemacs-elc &&
-          mv irchat-xemacs-elc irchat-xemacs.elc &&
-          mv irchat-gnuemacs-elc irchat-gnuemacs.elc
-     )
-     chmod a-w,a+r,u+w "$distname"/* &&
-     tar cvf "$distname"".tar" ./"$distname" &&
-     gzip -9 "$distname"".tar" &&
-     ls -l "$distname"".tar.gz" &&
-     rm -rf "$distname" &&
-     exit 0
+( cd "$distname" &&
+  ttt="/tmp/xxx.$$"
+  rm -f "$ttt"
+  for i in ./* ; do
+     cat "$i" |
+     gawk 'BEGIN { s = 1; }
+                 { if      (match($0, "^... BEGIN NODIST")) { s = 0 }
+                   else if (match($0, "^... END NODIST"))   { s = 1 }
+                   else if (s == 1) { print $0 } }' |
+     sed 's,\$Date[^$]*\$,'"`date -u '+$Date: 2001/06/07 14:25:09 $'`"',' > "$ttt" &&
+     rm -f "$i" &&
+     cat "$ttt" > "$i" &&
+     rm -f "$ttt"
+  done
+  true ) &&
+chmod 755 "$distname" &&
+( cd "$distname" &&
+  gmake xemacs-compact &&
+  mv irchat.elc irchat-xemacs-elc &&
+  gmake gnuemacs-compact &&
+  mv irchat.elc irchat-gnuemacs-elc &&
+  mv irchat-xemacs-elc irchat-xemacs.elc &&
+  mv irchat-gnuemacs-elc irchat-gnuemacs.elc ) &&
+chmod a-w,a+r,u+w "$distname"/* &&
+tar cvf "$distname"".tar" ./"$distname" &&
+gzip -9 "$distname"".tar" &&
+ls -l "$distname"".tar.gz" &&
+cp -p "$distname"/ChangeLog "$distname"/irchat-version.el . &&
+rm -rf "$distname" &&
+exit 0
 
 exit 2
 
